guest_list = ['Nicola Tesla', 'Albert Einstein', 'Linus Torvalds']
print(f"Dear {guest_list[0]}, {guest_list[1]} and {guest_list[2]} I found a bigger table, so there will be more guests at dinner")
guest_list.insert(0, 'Lewis Carrol')
guest_list.insert(2, 'Roald Dahl')
guest_list.append('Isaac Newton')
print(f"Dear {guest_list[0]}, I would love it if you could come to a dinner that I will be hosting with other great minds that humanity has had.")
print(f"Dear {guest_list[1]}, I would love it if you could come to a dinner that I will be hosting with other great minds that humanity has had.")
print(f"Dear {guest_list[2]}, I would love it if you could come to a dinner that I will be hosting with other great minds that humanity has had.")
print(f"Dear {guest_list[3]}, I would love it if you could come to a dinner that I will be hosting with other great minds that humanity has had.")
print(f"Dear {guest_list[4]}, I would love it if you could come to a dinner that I will be hosting with other great minds that humanity has had.")
print(f"Dear {guest_list[5]}, I would love it if you could come to a dinner that I will be hosting with other great minds that humanity has had.")
